import type { WeeklyReview } from "./weekly";
/** Synthetic aggregate fixture; no production campaign or homeowner data. */
export function weeklyFixture(): WeeklyReview {
  return {
    version: 1,
    asOf: "2026-09-11",
    generatedAt: "2026-09-11T12:00:00-05:00",
    sourceHash: "a".repeat(64),
    summary: {
      leads: 2,
      newLeads: 1,
      archived: 1,
      excludedTests: 1,
      linkedLeads: 1,
      requested: 100,
      packages: 1,
      uniqueAddresses: 99,
      invoiced: 1000,
      approvedSales: 1000,
      balance: 100,
      knownPaid: 50,
      confirmedMailed: null,
      collected: null,
      roas: null,
      profitRoi: null,
      budget: null,
    },
    months: [
      {
        month: "2026-09",
        requested: 100,
        leads: 2,
        sales: 1000,
        invoiced: 1000,
        vendorCost: 50,
        paid: 50,
        roas: null,
        profitRoi: null,
      },
    ],
    campaigns: [
      {
        id: "test-campaign",
        name: "Example neighborhood",
        audienceStrategy: "job_scheduled_neighborhood",
        touchType: "first_touch",
        requestedDate: "2026-09-01",
        plannedDate: null,
        reviewDate: "2026-09-22",
        reviewBasis: "request date only",
        requested: 100,
        leads: 1,
        invoiced: 1000,
        laterTouches: 0,
        confirmedMailed: null,
        decision: "Review",
        evidence: "https://mail.google.com/mail/#all/abc123",
      },
    ],
    roofs: [],
    profiles: [],
    invoices: [
      {
        number: "test-1",
        serviceMonth: "2026-09",
        invoiceDate: "2026-09-02",
        paidDate: "2026-09-03",
        amount: 50,
        pieces: 100,
        scope: "Partial cost",
        invoiceEvidence: "https://mail.google.com/mail/#all/abc123",
        paymentEvidence: "https://mail.google.com/mail/#all/abc124",
      },
    ],
    actions: [],
    gaps: ["Postage not reconciled"],
  };
}
